# Generated by Django 4.2.2 on 2023-07-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0002_syllabus_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='cs', related_query_name='cs', to='project2.student'),
        ),
    ]
